
configs: 'configs/configs.yaml'
alg: 'QLearning'
env: 'CyclicMDP'
trace: 'none'
lib: 'torch'
log_dir: 'log/'
eval: True
gamma: 0.99
lamb: 0.5
lr: 0.001
seed: 123456
batch_size: 32
num_steps: 30000
log_interval: 500
epsilon_start: 1
epsilon_final: 0.001
epsilon_decay: 500
window_size: 10
num_states: 3
eager: True


